site_name: FPTOJ WIKI
site_url: https://wiki.fptoj.com
theme:
  name: material
  features:
    - navigation.footer        
    - navigation.tabs          
    - navigation.tabs.sticky   
    - navigation.tracking     
    - toc.integrate 
    - toc.sticky          
    - search.suggest         
    - search.highlight          
    - content.code.copy         
    - content.code.annotate   
    - content.tabs.link        
    - header.autohide         

  logo: uploads/icon.svg
  palette:
    - scheme: default  
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang chế độ tối
    - scheme: slate  
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Chuyển sang chế độ sáng


nav:
  - Trang chủ: 
      - Home: index.md
      - Giới thiệu: about.md
      - Test Markdown: markdown.md
  - Thuật Toán:
      - Cơ Bản:
        - Đệ quy và Thuật toán quay lui: algo/basic/backtracking.md
        - Thuật toán tìm kiếm nhị phân: algo/basic/binary-search.md
        - Phép toán bit: algo/basic/bitwise-operators.md
        - Độ phức tạp thời gian: algo/basic/computational-complexity.md
        - 'Tôi đã học tin học như thế nào? Phần 1: vòng lặp': algo/basic/hoc-tin-the-nao-1.md
        - 'Tôi đã học tin học như thế nào? Phần 2: bắt đầu từ đâu': algo/basic/hoc-tin-the-nao-2.md
        - Meet In The Middle (MITM): algo/basic/meet-in-the-middle.md
        - Thuật toán sắp xếp: algo/basic/sorting.md
        - Một số Tài liệu hay về Thuật Toán: algo/basic/Tai-Lieu-Thuat-Toan.md
        - Kĩ thuật hai con trỏ: algo/basic/two-pointers.md
      - Đại Số:
        - Lũy thừa nhị phân: algo/algebra/binary_exponentation.md
        - Thuật toán Euclid: algo/algebra/euclid.md
        - Biến đổi Fourier nhanh - Fast Fourier transform: algo/algebra/fft-test.md
        - Cách tính số tổ hợp: algo/algebra/nCk.md
        - Kiểm tra số nguyên tố: algo/algebra/primality_check.md
        - Sàng nguyên tố: algo/algebra/prime_sieve.md
      - Cấu trúc dữ liệu:
        - Mảng và danh sách liên kết: algo/data-structures/array-vs-linked-lists.md
        - Cấu trúc của cây Palindrome: algo/data-structures/Cây-Palindrome.md
        - Tổng quan về Cấu Trúc Dữ Liệu: algo/data-structures/data-structures-overview.md
        - Hàng đợi hai đầu (deque) và Bài toán tìm max-min trong đoạn tịnh tiến: algo/data-structures/deque-min-max.md
        - Deque - hàng đợi hai đầu: algo/data-structures/Deque.md
        - Disjoint Set Union: algo/data-structures/disjoint-set-union.md
        - Disjoints Sets: algo/data-structures/disjoint-set.md
        - Cây chỉ số nhị phân 2 chiều (BIT 2 chiều): algo/data-structures/fenwick-2d.md
        - Cây chỉ số nhị phân (Binary Indexed Tree): algo/data-structures/fenwick.md
        - Bảng băm (Hash Table): algo/data-structures/hash-table.md
        - Heavy-Light Decomposition (HLD): algo/data-structures/heavy-light-decomposition.md
        - Interval Tree trên tập đoạn thẳng: algo/data-structures/interval-tree-tap-doan-thang.md
        - Lowest Common Ancestor (LCA) - Binary Lifting: algo/data-structures/lca-binlift.md
        - Các phương pháp giải bài toán LCA: algo/data-structures/lca.md
        - 'Chia căn (sqrt decomposition) và ứng dụng: Phần 2': algo/data-structures/mo-algorithm.md
        - Cấu trúc dữ liệu: algo/data-structures/overview-data-structures.md
        - Persistent Data Structures: algo/data-structures/persistent-data-structures.md
        - Mảng cộng dồn và mảng hiệu: algo/data-structures/prefix-sum-and-difference-array.md
        - Range Minimum Query (RMQ) - Sparse Table: algo/data-structures/rmq.md
        - Cây Phân Đoạn (cơ bản): algo/data-structures/segment-tree-basic.md
        - Tất tần tật về Cây Phân Đoạn (Segment Tree): algo/data-structures/segment-tree-extend.md
        - Skip Lists: algo/data-structures/Skip-Lists.md
        - 'Chia căn (sqrt decomposition) và ứng dụng: Phần 1': algo/data-structures/sqrt-decomposition.md
        - Stack (ngăn xếp): algo/data-structures/Stack.md
        - Mảng hậu tố (Suffix Array): algo/data-structures/suffix-array.md
        - Suffix Automaton: algo/data-structures/suffix-automaton.md
        - Trie: algo/data-structures/trie.md
      - Quy hoạch động:
        - Quy hoạch động cơ bản (Phần 1): algo/dp/basic-dynamic-programming-1.md
        - Quy hoạch động cơ bản (Phần 2): algo/dp/basic-dynamic-programming-2.md
        - Một số bài toán quy hoạch động điển hình: algo/dp/basic-problems.md
        - Một số kĩ thuật tối ưu hoá thuật toán Quy Hoạch Động: algo/dp/Mot-so-ky-thuat-toi-uu-hoa-thuat-toan-Quy-Hoach-Dong.md
        - Một vài bài tập về Palindrome: algo/dp/palindrome-problems.md
        - Phân tích về QHĐ - Thầy Lê Minh Hoàng: algo/dp/thac-mac-ve-qhd.md
      - Games:
        - Giải thuật cắt tỉa Alpha-beta: algo/games/Giai-Thuat-Cat-Tia-Alpha-beta.md
      - Hình học:
        - 'Hình học tính toán phần 1: Những khái niệm cơ bản': algo/geometry/basic-geometry-1.md
        - 'Hình học tính toán phần 2: Sự giao nhau của đường thẳng và các ứng dụng': algo/geometry/basic-geometry-2.md
        - Thuật toán đường quét: algo/geometry/Sweep-Line.md
      - Lý thuyết Đồ Thị:
        - BFS (Breadth-first search): algo/graph-theory/breadth-first-search.md
        - Thuật toán phân tách trọng tâm - Centroid decomposition: algo/graph-theory/centroid-decomposition.md
        - Cây DFS (Depth-First Search Tree) và ứng dụng: algo/graph-theory/Depth-First-Search-Tree.md
        - Đường đi - Chu trình Euler: algo/graph-theory/euler-cycle.md
        - Đường đi Euler trên cây: algo/graph-theory/euler-tour-on-tree.md
        - Các chủ đề cơ bản về đồ thị: algo/graph-theory/everything.md
        - Bài toán Luồng cực đại trên mạng: algo/graph-theory/flow.md
        - Bài toán LUBENICA: algo/graph-theory/lubenica-vnoj.md
        - Bài toán tìm cây khung nhỏ nhất trong đồ thị: algo/graph-theory/minimum-spanning-tree.md
        - Các thuật toán về tìm đường đi ngắn nhất: algo/graph-theory/shortest-path.md
        - Sắp xếp Tô-pô (Topological Sort): algo/graph-theory/topological-sort.md
      - Toán:
        - Lý thuyết trò chơi: algo/math/game-theory.md
        - Hàm Mobius: algo/math/Ham-Mobius.md
        - Số học 4.5 - Nghịch đảo modulo: algo/math/modular-inverse.md
        - Hàm nhân tính: algo/math/multiplicative-function.md
      - Tìm Kiếm:
        - Local Search: algo/search/Local-Search.md
      - Kỹ Năng Thi:
        - Tổng hợp các lời khuyên cho các kỳ thi: algo/skill/Ki-nang-thi-cu.md
        - Kinh nghiệm thi VOI: algo/skill/Kinh-nghiem-thi-VOI.md
        - Tự code, tự chấm, tự sướng - Bí kíp thi offline: algo/skill/viet-trinh-cham.md
      - Xâu kí tự:
        - Xử lý xâu: algo/string/basic.md
        - 'Hash: A String Matching Algorithm': algo/string/hash.md
        - Thuật toán KMP: algo/string/kmp.md
        - Thuật toán Manacher: algo/string/manacher.md
        - Z-function: algo/string/z-algo.md
      - Mẹo:
        - Phỏng Vấn Team IOI VN 2017: Phỏng-vấn-team-IOI-VN-2017.md
        - ALAKE: others/vojsol/ALAKE.md
        - Sum-constrained convex optimization: algo/trick/convex_greedy.md
        - Khử nhân ma trận: algo/trick/counting-without-matrix-multiplication.md
        - FFT: algo/trick/FFT.md
        - Nhân ma trận (Matrix multiplication): algo/trick/matrix-multiplication.md
        - Meet In The Middle (MITM): algo/trick/mitm.md
        - Rời rạc hoá và ứng dụng: algo/trick/Roi-rac-hoa-va-ung-dung.md
  - Computer Science (Khoa học máy tính):
    - Crypto:
      - Mật mã và Code: cs/crypto/Cipher-Tools.md
      - Public Key Cryptography: cs/crypto/Public-Key-Cryptography.md
      - Cipher:
        - ROT13: cs/crypto/cipher/ROT13.md
    - Xử lý ảnh:
      - Seam Carving Algorithm: cs/imageprocessing/Seam-Carving.md
      - Hướng dẫn cài đặt OpenCV trên Windows: cs/imageprocessing/setup-opencv-windows.md 
  - Ngôn Ngữ Lập Trình:
    - Con trỏ trong C/C++: languages/cpp/pointers.md
    - Xâu trong C++: languages/cpp/string.md
    - Hoài niệm về Pascal - Lê Minh Hoàng: others/Pascal-Vi-sao.md
  - Dịch Thuật:
    - Functional Programming - Phần 1: translate/functional-programming-part-1.md
    - Codeforces:
      - Cài đặt cây phân đoạn hiệu quả (Efficient and easy segment trees): translate/codeforces/Efficient-and-easy-segment-trees.md
      - Bảng băm (Hash Tables): translate/codeforces/hash-table.md
      - Palindrome tree: translate/codeforces/palindrome-tree.md
      - Queue & Stack: translate/codeforces/stack-queue.md
      - Z Algorithm: translate/codeforces/z-algo.md
    - E-Maxx:
      - Aho Corasick: translate/emaxx/Aho-Corasick.md
      - Tìm kiếm tam phân - Ternary Search: translate/emaxx/Tim-kiem-tam-phan-Ternary-Search.md
    - Nâng Cao:
      - Định lý Lucas: translate/he/Lucas-theorem.md
      - Số học 2 - Số nguyên tố, Sàng Eratosthenes: translate/he/Number-Theory-2.md
      - Số học 3 - Tính (a^b) % c: translate/he/Number-Theory-3.md
      - Số học 4 - Phi hàm Euler: translate/he/Number-Theory-4.md
      - Số học 5 - Các kiến thức cơ bản về Tổ hợp (Combinatorics): translate/he/Number-Theory-5.md
      - Số học 6 - Xác suất (Probabilities): translate/he/Number-Theory-6.md
      - Số học 7 - Bao hàm - Loại trừ (Inclusion-Exclusion): translate/he/Number-Theory-7.md
      - Số học 1 - Modulo & gcd: translate/he/So-hoc-Phan-1-Modulo-gcd.md
      - Định lý Wilson: translate/he/Wilsons-theorem.md
    - Máy học (Machine Learning - ML):
      - 'Machine Learning 101 (1): Làm quen': cs/ml/machine-learning-101.md
      - PyTorch Là Gì?: translate/PyTorch-la-gi.md
      - Machine Learning - Classification - phần 1: translate/ml/Machine-Learning-Classification-phan-1.md
      - Machine Learning - Classification - phần 2: translate/ml/Machine-Learning-Classification-phan-2.md
      - Machine Learning - Classification - phần 3: translate/ml/Machine-Learning-Classification-phan-3.md
    - Quora:
      - Hàm Mobius: translate/quora/mobius-function.md
    - Topcoder:
      - Độ phức tạp tính toán: translate/topcoder/Computational-Complexity-Section-1.md
      - Độ phức tạp tính toán - phần 2: translate/topcoder/Computational-Complexity-Section-2.md
      - Nhập môn Quy hoạch động: translate/topcoder/dynamic-programming.md
      - Fun with Bits: translate/topcoder/fun-with-bits.md
      - Thuật toán Tham lam: translate/topcoder/Greedy-is-Good.md
      - Xác suất: translate/topcoder/Hieu-ve-xac-suat.md
      - Kĩ năng đọc đề Topcoder: translate/topcoder/How-to-Dissect-a-Topcoder-Problem-Statement.md
      - Nghệ thuật giải bài: translate/topcoder/How-to-Find-a-Solution.md
      - Toán học trong Tin học: translate/topcoder/Mathematics-for-Topcoders.md
      - Luồng cực đại trên mạng - Maxflow network: translate/topcoder/max-flow-1-luong-cuc-dai-tren-mang-1.md
      - 'Những cách tiếp cận bài toán: Phần 1': translate/topcoder/Planning-an-Approach-to-a-Topcoder-Problem-Part-1.md
      - 'Những cách tiếp cận bài toán: Phần 2': translate/topcoder/Planning-an-Approach-to-a-Topcoder-Problem-Part-2.md
      - Bài toán RMQ và bài toán LCA: translate/topcoder/Range-Minimum-Query-and-Lowest-Common-Ancestor.md
      - Tầm Quan Trọng Của Thuật Toán: translate/topcoder/The-Importance-of-Algorithm.md
      - Sử dụng Regex: translate/topcoder/Using-Regular-Expression.md
    - USACO:
      - Viết lời giải chiến thắng trong kì thi: translate/USACO/Crafting-Winning-Solutions.md
    - Wcipeg:
      - Giải thích trực quan về bao lồi trên mặt phẳng: translate/wcipeg/Bao-lồi.md
      - Binary Heap: translate/wcipeg/Binary-Heap.md
      - Kĩ thuật bao lồi (Convex Hull Trick): translate/wcipeg/Convex-Hull-Trick.md
      - Bao lồi (Convex Hull): translate/wcipeg/Convex-Hull.md
      - Bài toán luồng cực đại: translate/wcipeg/Flows.md
      - Thuật toán Knuth-Morris-Pratt (KMP): translate/wcipeg/kmp.md
      - Cây (Tree): translate/wcipeg/tree.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details     
  - pymdownx.extra 
  - pymdownx.magiclink 
  - pymdownx.pathconverter:
      base_path: "docs"
  - pymdownx.arithmatex:
      generic: true


extra:
  generator: false               
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KienPC1234/fptoj_wiki

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/jquery-3.7.1.min.js
  - js/webjs.js
  
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css